- name: Install Python and Docker
  become: true
  hosts: 127.0.0.1
  roles:
    - geerlingguy.pip
    - geerlingguy.docker
  tasks:
  - name: install requests
    become: true
    pip:
      name:
        - requests
        - docker

- name: configure geth node 1
  hosts: 127.0.0.1
  roles:
    - geth
  vars:
    path: /home/vagrant/geth-cluster-files
    geth_evmc_repo: https://github.com/ewasm/go-ethereum
    geth_evmc_branch: tantalus
    node_name: miner1
    genesis_url: https://gist.githubusercontent.com/jwasinger/8ea1852653fbffcd11d5f84e968764ab/raw/e28bd4a8fec0307e26caa18e2ea0d283e2defe1a/genesis.json
    etherbase: a8c3eeb2915373139bcfc287d4ae9e660d734881
    bootnodes: ""
    listen_port: 30304
    nodekey: dc90f8f7324f1cc7ba52c4077721c939f98a628ed17e51266d01c9cd02940339
